---
- name: Writing a test playbook
  hosts: all
  gather_facts: yes
  become: yes
  tasks:
    - name: Task1
      shell: sudo apt update
    - name: Task2
      shell: df -h
    - name: Task3
      shell: pwd
    - name: Task3
      shell: ll
