---
- name: Provision an EC2 instance
  hosts: localhost
  become: yes
  gather_facts: no
  vars:
    aws_region: ap-east-1
    key_name: Awx_lab
    instance_type: t2.micro
    image_id: ami-04a81a99f5ec58529
    security_group: launch-wizard-3
    subnet_id: subnet-03b85d94de5e2b99c
  tasks:
   - name: Install EC2 Instance using Shell
     ansible.builtin.shell: >
       aws ec2 run-instances \
       --image-id ami-04a81a99f5ec58529 \
       --count 1 \
       --instance-type t2.micro \
       --key-name Awx_lab \
       --subnet-id subnet-03b85d94de5e2b99c \
       --security-group-ids sg-060a4fbcb6c4f5399
