---
- name: Ubuntu Server Patching
  hosts: all
  become: yes  # Ensure the tasks are run as root
 
  tasks:
    - name: Update the apt package index
      apt:
        update_cache: yes
 
    - name: Upgrade all packages to the latest version
      apt:
        upgrade: dist
 
    - name: Remove unnecessary packages
      apt:
        autoremove: yes
 
    - name: Clean up the local repository of retrieved package files
      apt:
        autoclean: yes
 
    - name: Reboot the server if needed
      reboot:
        reboot_timeout: 60
      when: ansible_facts.packages_changed | default(false)
 
  handlers:
    - name: Reboot the server
      reboot:
        reboot_timeout: 60
