---
- name: Provision an EC2 instance
  hosts: localhost
  become: yes
  gather_facts: no
  collections: amazon.aws
  vars:
    aws_region: ap-east-1
    key_name: Awx_lab
    instance_type: t2.micro
    image_id: ami-04a81a99f5ec58529
    security_group: launch-wizard-3
    subnet_id: subnet-03b85d94de5e2b99c
  tasks:
    - name: Create a security group
      amazon.aws.ec2_group:
        name: "{{ security_group }}"
        description: "Security group for EC2 instance"
        region: "{{ aws_region }}"
        rules:
          - proto: tcp
            from_port: 22
            to_port: 22
            cidr_ip: 0.0.0.0/0
        rules_egress:
          - proto: -1
            from_port: -1
            to_port: -1
            cidr_ip: 0.0.0.0/0
        state: present
      register: security_group_result
 
    - name: Debug security group creation result
      debug:
        var: security_group_result
 
    - name: Launch EC2 instance
      amazon.aws.ec2_instance:
        name: TestingVMM
        key_name: "{{ key_name }}"
        instance_type: "{{ instance_type }}"
        image_id: "{{ image_id }}"
        region: "{{ aws_region }}"
        vpc_subnet_id: "{{ subnet_id }}"
        security_group: "{{ security_group }}"
        wait: yes
      register: ec2
 
    - name: Debug EC2 launch result
      debug:
        var: ec2
 
    - name: Output instance details
      debug:
        msg: |
          EC2 instance created:
          - Instance ID: {{ ec2.instances[0].id }}
          - Public IP: {{ ec2.instances[0].public_ip }}
