---
- name: Provision an EC2 instance in AWS
  hosts: localhost
  become: yes
  gather_facts: yes
  vars:
    instance_type: t2.micro
    ami: ami-04a81a99f5ec58529
    key_name: Awx_lab1
    region: us-east-1 
    security_group: default
    instance_count: 1
    instance_name: AWX-EC2-Instance
 
  tasks:
    - name: Launch EC2 Instance
       amazon.aws.ec2_instance:
        key_name: "{{ key_name }}"
        instance_type: "{{ instance_type }}"
        image: "{{ ami }}"
        wait: yes
        region: "{{ region }}"
        group: "{{ security_group }}"
        instance_tags:
          Name: "{{ instance_name }}"
        exact_count: "{{ instance_count }}"
        count_tag:
          Name: "{{ instance_name }}"
        assign_public_ip: yes
      register: ec2
 
    - name: Wait for the instance to be in running state
      amazon.aws.ec2_instance_info:
        region: "{{ region }}"
        filters:
          instance-state-name: running
          tag:Name: "{{ instance_name }}"
      register: ec2_info
 
    - name: Display the public IP address of the instance
      debug:
        msg: "EC2 Instance Public IP: {{ ec2_info.instances[0].public_ip_address }}"
