---
- name: Create EC2 instance using AWS CLI
  hosts: localhost
  become: yes
  gather_facts: yes
  vars:
    region: "us-east-1"
    instance_type: "t2.micro"
    ami_id: "ami-04a81a99f5ec58529"
    key_name: "Aws_lab"
    security_group: "sg-09656da5cdd3a0b7b"
    subnet_id: "subnet-03b85d94de5e2b99c"
    tag_name: "Ansible_AWX_EC2"
 
  tasks:
    - name: Run AWS CLI command to create EC2 instance
      ansible.builtin.shell: >
        aws ec2 run-instances \
        --region {{ region }} \
        --instance-type {{ instance_type }} \
        --image-id {{ ami_id }} \
        --key-name {{ key_name }} \
        --security-group-ids {{ security_group }} \
        --subnet-id {{ subnet_id }} \
        --tag-specifications 'ResourceType=instance,Tags=[{Key=Name,Value={{ tag_name }}}]' \
        --query 'Instances[0].InstanceId' \
        --output text
      register: ec2_instance_id
 
    - name: Output EC2 instance ID
      ansible.builtin.debug:
        var: ec2_instance_id
